# Generated by Django 5.1.4 on 2024-12-10 17:18

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistgroup',
            name='code',
            field=models.CharField(default=app.models.generate_group_code, max_length=10, unique=True),
        ),
    ]
