# Generated by Django 5.1.4 on 2024-12-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_wishlistgroup_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistgroup',
            name='budget_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wishlistgroup',
            name='submission_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
