# Generated by Django 5.1.4 on 2024-12-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_category_alter_wishlistitem_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistgroup',
            name='budget_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default='unlimited', max_digits=10, null=True),
        ),
    ]
