# Generated by Django 5.1.4 on 2024-12-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_wishlistgroup_budget_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistgroup',
            name='budget_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
