# Generated by Django 5.1.4 on 2024-12-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
