# Generated by Django 5.1.4 on 2024-12-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_wishlistitem_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistgroup',
            name='is_launched',
            field=models.BooleanField(default=False),
        ),
    ]
